force-app/main/default/objects/Static_User__mdt/Static_User__mdt.object-meta.xml
<CustomObject>
    <label>Static User</label>
    <pluralLabel>Static Users</pluralLabel>
</CustomObject>

force-app/main/default/objects/Static_User__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The 18 character GUID for the user</description>
    <inlineHelpText>The 18 character GUID for the use</inlineHelpText>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Static_User__mdt/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Type of User. "Data Loader", "Release User", "Leena"</description>
    <inlineHelpText>Type of User. "Data Loader", "Release User", "Leena"</inlineHelpText>
    <label>User Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StaticUser.cls
public class StaticUser {

    public static final String DATA_LOADER_USER_TYPE = 'Data Loader';

    // Data Loader Ids are in Custom Metadata Type
    // Does not work as MDT data is not available in test context
    public static Set<Id> getDataLoaderIds() {
        Set<Id> userIds = new Set<Id>();

        List<Static_User__mdt> staticUsers = [SELECT User_Id__c FROM Static_User__mdt WHERE User_Type__c = :DATA_LOADER_USER_TYPE];
        for ( Static_User__mdt staticUser : staticUsers) {
            userIds.add( staticUser.User_Id__c);
        }
        return userIds;
    }
}