force-app/main/default/objects/Static_User__mdt/Static_User__mdt.object-meta.xml
<CustomObject>
    <label>Static User</label>
    <pluralLabel>Static Users</pluralLabel>
</CustomObject>

force-app/main/default/objects/Static_User__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The 18 character GUID for the user</description>
    <inlineHelpText>The 18 character GUID for the use</inlineHelpText>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Static_User__mdt/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Type of User. "Data Loader", "Release User", "Leena"</description>
    <inlineHelpText>Type of User. "Data Loader", "Release User", "Leena"</inlineHelpText>
    <label>User Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StaticUserTest.cls
@isTest (SeeAllData=false)
private class StaticUserTest {

    static TestMethod void testQueryDataLoaderUsers() {
        // Arrange
        Set<Id> dataLoaderIds = StaticUser.getDataLoaderIds();
        List<User> dataLoaderUsers = new List<User>();
        List<Static_User__mdt> staticUsers = [SELECT User_Id__c FROM Static_User__mdt WHERE User_Type__c = :StaticUser.DATA_LOADER_USER_TYPE];

        // Act
        Test.startTest();
        dataLoaderUsers = [SELECT Username FROM User WHERE Id in :dataloaderIds];
        Test.stopTest();

        // Assert
        System.assertEquals( staticUsers.size(), dataLoaderUsers.size(), 'Number of data loader should be ' + staticUsers.size());
    }

    static TestMethod void testNoEffectOnSOQLLimits() {
        // Arrange
        Integer beforeQueryCount = 0;
        Integer afterQueryCount = 0;

        // Assert

        // Act
        Test.startTest();
        beforeQueryCount = Limits.getQueries();
        Set<Id> dataLoaderIds = StaticUser.getDataLoaderIds();
        afterQueryCount = Limits.getQueries();
        Test.stopTest();

        // Assert
        System.assertEquals( beforeQueryCount, afterQueryCount, 'SOQL Queries should not change with StaticUser.getDataLoaderIds()');
    }
}